CREATE TABLE T_BLOG (
  N_ID INT(11) NOT NULL AUTO_INCREMENT,
  C_TITLE VARCHAR(50) DEFAULT NULL,
  C_CONTENT TEXT,
  N_TYPE INT(11) DEFAULT NULL,
  N_USERID INT(11) DEFAULT NULL,
  DT_CREATETIME DATETIME DEFAULT NULL,
  DT_EDITTIME DATETIME DEFAULT NULL,
  PRIMARY KEY (N_ID)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;


CREATE TABLE T_BLOG_COMMENT (
  T_ID INT(11) NOT NULL AUTO_INCREMENT,
  T_PID INT(11) DEFAULT NULL,
  T_REP_ID INT(11) DEFAULT NULL,
  T_USER_ID INT(11) DEFAULT NULL,
  T_COMMENT TEXT,
  DT_CREATETIME DATETIME DEFAULT NULL,
  DT_EDITTIME DATETIME DEFAULT NULL,
  PRIMARY KEY (T_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE T_USER (
  N_ID INT(11) NOT NULL AUTO_INCREMENT,
  C_USERNAME VARCHAR(30) DEFAULT NULL,
  C_PASSWORD VARCHAR(50) DEFAULT NULL,
  C_EMAIL VARCHAR(50) DEFAULT NULL,
  DT_CREATE_TIME DATETIME DEFAULT NULL,
  PRIMARY KEY (N_ID)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;

CREATE TABLE T_LEAVE_MESSAGE (
  N_ID INT(11) NOT NULL AUTO_INCREMENT,
  C_TITLE VARCHAR(50) DEFAULT NULL,
  C_CONTENT TEXT,
  N_USERID INT(11) DEFAULT NULL,
 C_USERNAME INT(11) DEFAULT NULL,
  DT_CREATETIME DATETIME DEFAULT NULL,
  DT_EDITTIME DATETIME DEFAULT NULL,
  PRIMARY KEY (N_ID)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;

CREATE TABLE T_CODEPUSH_RECORD (
  N_ID INT(11) NOT NULL AUTO_INCREMENT,
  C_PUSH_ID VARCHAR(50) DEFAULT NULL,
  C_COMMITTER_EMAIL VARCHAR(50) DEFAULT NULL,
  C_COMMITTER_NAME VARCHAR(50) DEFAULT NULL,
  C_COMMITTER_SHA VARCHAR(50) DEFAULT NULL,
  C_COMMITTER_MSG VARCHAR(50) DEFAULT NULL,
  REF VARCHAR(50) DEFAULT NULL,
  DT_CREATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (N_ID)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;

CREATE TABLE TPOLYMERIZATIONELEMENT (
  ID INT NOT NULL,
  TITLE VARCHAR(300) DEFAULT NULL,
  URL VARCHAR(300) DEFAULT NULL,
  TYPE INT DEFAULT NULL,
  DATE DATETIME DEFAULT NULL,
  EXT1 VARCHAR(300) DEFAULT NULL,
  EXT2 VARCHAR(300) DEFAULT NULL,
  EXT3 VARCHAR(300) DEFAULT NULL,
  EXT4 VARCHAR(300) DEFAULT NULL,
  EXT5 VARCHAR(300) DEFAULT NULL,
  PRIMARY KEY (ID,TYPE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE TGASOLINE (
  ID VARCHAR(50) NOT NULL,
  BDRQ DATE DEFAULT NULL,
  PRICE DECIMAL(5,2) DEFAULT NULL,
  BDFD DECIMAL(5,2) DEFAULT NULL,
  TYPE INT(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;





